### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by tsunaliew** [bestiannn/genshin-banner-countdown#4]
Hi, I like your website and I plan to use it in my discord channel with MonitoRSS bot to track new banner and auto notify, is it possible to add RSS feed?

**Comment by bestiannn** [comment]
Hello! I just added to https://genshin-banner-countdown.netlify.app/api/rss for track the countdown in the three servers, also you can watch https://genshin-banner-countdown.netlify.app/api/ or https://genshin-banner-countdown.netlify.app/api/actual for use the API of the web.
